### ISSUE TITLE
Warning: Update Azure Developer CLI.

### ISSUE THREAD

**Issue by nathaniel-msft** [Azure-Samples/aks-store-demo#103]
**Describe the solution you'd like**
Update AZD CLI to prevent future issues by using the most recent image.

**Additional context**
`WARNING: your version of azd is out of date, you have 1.5.0 and the latest version is 1.5.1`

**Comment by pauldotyu** [comment]
@nathaniel-msft, this is when you attempt to run azd within Codespaces, right?

**Comment by pauldotyu** [comment]
Update. I just created a new Codespace and it seems to have the correct version of `azd`. I see 1.5.1 now, so you may want to do a "full rebuild" of the container. The devcontainer configuration is set to install the "[latest](https://github.com/Azure-Samples/aks-store-demo/blob/8334f7cca95052c053bcf5b9a4144bfdfab489b6/.devcontainer/devcontainer.json#L10)" version of azd.
