### ISSUE TITLE
Host this repository helm chart publicly

### ISSUE THREAD

**Issue by dtzar** [Azure-Samples/aks-store-demo#106]
**Describe the solution you'd like**
As a user/operator, I'd like to be able to install the application utilizing the helm chart from a hosted chart repository so that I can easily deploy the application with various parameters onto various clusters, especially with gitops agents such as ArgoCD or Flux.

**Describe alternatives you've considered**
Cloning the repository locally and then running commands takes a lot longer and also doesn't work (at all or easily) with GitOps agent deployments.

**Comment by pauldotyu** [comment]
Can now see chart info with this command.

```
helm show chart oci://ghcr.io/azure-samples/aks-store-demo/charts/aks-store-demo-chart --version 1.0.0
```
