### ISSUE TITLE
Review and update feature registrations in azd-hooks/preprovision.{ps1,sh}

### ISSUE THREAD

**Issue by clarenceb** [Azure-Samples/aks-store-demo#139]
Not all feature flags are required as some of these previously preview features are now GA.

See files:

* https://github.com/Azure-Samples/aks-store-demo/blob/main/azd-hooks/preprovision.sh
* https://github.com/Azure-Samples/aks-store-demo/blob/main/azd-hooks/preprovision.ps1

GAs:

* KEDA (don't require `AKS-KedaPreview` feature flag)
* Prometheus (don't require `AKS-PrometheusAddonPreview` feature flag)

The other features still appear to be in public preview.

**Comment by pauldotyu** [comment]
Thanks for raising this @clarenceb!
