### ISSUE TITLE
Missing closing '}' 

### ISSUE THREAD

**Issue by charris-msft** [Azure-Samples/aks-store-demo#151]
**Describe the bug**
```
ERROR: error executing step command 'deploy --all': failed running pre hooks: 'predeploy' hook failed with exit code: '1', Path: 'azd-hooks\predeploy.ps1'. : exit code: 1, stdout: , stderr: ParserError: C:\git\azure_agent\aks-store-demo\azd-hooks\predeploy.ps1:79
Line |
  79 |  if ($env:AZURE_SERVICE_BUS_HOST) {
     |                                   ~
     | Missing closing '}' in statement block or type definition.
```

![image](https://github.com/Azure-Samples/aks-store-demo/assets/74415662/58562d77-d5d6-419d-92bc-a3a7e312ce8e)

**To Reproduce**
1. Run `azd up`
2. Wait a long time
3. See error

**Expected behavior**
No error occurs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by pauldotyu** [comment]
Thanks for the heads up @charris-msft will take a look.
