### ISSUE TITLE
Adding ability to deploy with azd CLI

### ISSUE THREAD

**Issue by chanezon** [Azure-Samples/aks-store-demo#58]
**Is your feature request related to a problem? Please describe.**
It's great when sample apps can get deployed with azd up

**Describe the solution you'd like**
add azd support to this sample like in https://github.com/Azure-Samples/azure-search-openai-demo

**Describe alternatives you've considered**
alternatives are to continue to copy and paste CLI commands to deploy the app in 15 steps

**Additional context**
A good example is https://github.com/Azure-Samples/azure-search-openai-demo
or https://github.com/Azure-Samples/azure-search-openai-demo-csharp

**Comment by chzbrgr71** [comment]
I like this idea. We need to add this to our list. 

FYI, we would likely replace Mongo and Rabbit with Cosmos and Service Bus for that. We've intentionally used OSS tools for the simple walkthrough, but the other tutorials for using Azure PaaS services are being written as we speak. Would be a good place to use the `azd up` scenario
