### ISSUE TITLE
Failed to run ''azd up" command in Dev Container and Codespace

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure-Samples/aks-store-demo#92]
**Describe the issue:**
When running` azd up ` in Dev Container and Codespace , get error as follow:
![image](https://github.com/Azure-Samples/aks-store-demo/assets/141405558/7d39bc7c-09a7-4c81-b639-0ec72cc550c6)

**Environment:**

   - OS: Dev Container ,   Codespace 
   - azd version:  1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Repro Steps:**

1. Clone the repo to local and reopen with Dev Container and Codespace.
2. Run `azd auth login`.
3. Run `azd up` .

**Expected behavior:**
Run `azd up` can pass in Dev Container and Codespace.

@hemarina and @pauldotyu for notification.

**Comment by pauldotyu** [comment]
@zhangjiale-64 thanks for testing and submitting this issue. Unfortunately `azd auth login` is not enough. Terraform requires Azure CLI login context, so in addition to `azd auth login` you should do `az login` and it will work.

**Comment by zhangjiale-64** [comment]
> @zhangjiale-64 thanks for testing and submitting this issue. Unfortunately `azd auth login` is not enough. Terraform requires Azure CLI login context, so in addition to `azd auth login` you should do `az login` and it will work.

@pauldotyu  After do  `az login` and it works. This issue will no longer be reproduced and we will close this issue.
