### ISSUE TITLE
Add Bicep support

### ISSUE THREAD

**Issue by nathaniel-msft** [Azure-Samples/aks-store-demo#98]
**Is your feature request related to a problem? Please describe.**

Add Bicep support to the repo.

**Describe the solution you'd like**

Create a manual setup to switch between terraform or bicep.

**Describe alternatives you've considered**

We thought of making a new repo, but it's difficult to maintain and results in desynced content.

**Additional context**

This will be used in AKS Docs on Learn.

**Comment by jongio** [comment]
1. Move tf files to /infra/terraform
2. Put bicep files in /infra/bicep
3. Update azure.yaml to use terraform by default
4. Add new azure-bicep.yaml file to root of repo.
5. Add readme note that they need to rename the azure-bicep.yaml file to azure.yaml to use bicep.
